### ISSUE TITLE
No matching arp response on MacOS

### ISSUE THREAD

**Issue by smilix** [j-keck/arping#2]
Hi, 

I'm testing the arping cli on MacOS and I've the problem that I get no matching response.
```
sudo -E ./arping -t 1s -v 192.168.2.3                                                                                        holger@happle
Password:
search usable interface
 OTHER NET:    lo0                     up|loopback|multicast
      DOWN:   gif0                     pointtopoint|multicast
      DOWN:   stf0                     0
    USABLE:    en0  20:c9:d0:7a:fa:31  up|broadcast|multicast
search available /dev/bpfX
  open failed: /dev/bpf0 - open /dev/bpf0: resource busy
  open failed: /dev/bpf1 - open /dev/bpf1: resource busy
  open success: /dev/bpf2
arping '192.168.2.3' over interface: 'en0' with address: '192.168.2.211'
ignore received arp: srcIP: '<nil>', srcMac: '02:d3:ff:ff:ff:ff:ff:ff:c0:a8:02:03'
ignore received arp: srcIP: '<nil>', srcMac: '02:03:20:c9:d0:7a:fa:31:c0:a8:02:d3:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00'
ignore received arp: srcIP: '<nil>', srcMac: '02:e2:00:00:00:00:00:00:c0:a8:02:01:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00'
timeout
```

With the "original" arping I get a response: 
```
/usr/local/sbin/arping 192.168.2.3                                                                                           holger@happle
ARPING 192.168.2.3
60 bytes from b8:27:eb:c4:2e:5f (192.168.2.3): index=0 time=5.100 msec
```

I've captured the packets also with Wireshark and arping (the go version) was correct in the number of responses. There are 3 arp packets. The first one was a correct reply, but somehow arping could not recognize it. 
Any ideas?

**Comment by j-keck** [comment]
hey,

hard to reproduce.


can you please attach (or send per mail) the wireshark dump?

thanks, juergen

**Comment by smilix** [comment]
Here is dump for this: https://filetea.me/t1s61rlI6qwRoW9trfKuI5pQg

**Comment by j-keck** [comment]
no idea! but it's interesting.

i don't understand why in your output the 'srcIP' is 'nil' and the 'srcMac' are messed up.
something go wrong when the packet are parsed.

i can't reproduce what's happening on your site.
my test with your provided pcap file:

 * my workstation is a freebsd machine
 * test interface is 're0': 
```
root@main:~ # ifconfig re0 | grep -E 'ether|inet'
	ether e0:cb:4e:d5:ca:4e
	inet 192.168.2.211 netmask 0xffffff00 broadcast 192.168.2.255 
```
 * ` ./arping -t 10s -v 192.168.2.3`
 * at the same time, i replay your pcap dump (with 

**result:**
```
root@main:~ ./arping -t 10s -v 192.168.2.3
search usable interface
    USABLE:    re0  e0:cb:4e:d5:ca:4e  up|broadcast|multicast
search available /dev/bpfX
  open success: /dev/bpf0
arping '192.168.2.3' over interface: 're0' with address: '192.168.2.211'
ignore received arp: srcIP: '192.168.2.211', srcMac: 'e0:cb:4e:d5:ca:4e'
ignore received arp: srcIP: '192.168.2.211', srcMac: '20:c9:d0:7a:fa:31'
process received arp: srcIP: '192.168.2.3', srcMac: 'b8:27:eb:c4:2e:5f'
192.168.2.3 (b8:27:eb:c4:2e:5f) 1274,789 usec
```

the first entry is from the arping, the rest are the replay from your pcap dump:
![wireshark](https://cloud.githubusercontent.com/assets/3081095/16169853/d01e55a2-353d-11e6-9630-4b658196dcdf.png)

----
i don't have a macos by hand to test this. but maybe at wednesday i meet someone where i can test it under macos.

sorry - i report back at thursday.

**Comment by j-keck** [comment]
ah - what kind of mac do you have? 

is it a intel cpu?
osx version?

**Comment by j-keck** [comment]
hey, 

i committed a fix in the dev branch.
can you please test it?

thanks

**Comment by smilix** [comment]
The fix is working, I get proper results now. Big thanks!
