### ISSUE TITLE
Malformed gARP packet

### ISSUE THREAD

**Issue by TothFerenc** [j-keck/arping#3]
Hello,

I would like to use this Go arping implementation in a containerized (k8s) environment for CNI purposes.
I started a Pod(1), which has eth1 interface for packet capturing.
I started another Pod(2), which has eth1 as follows:
```
105: eth1@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc noqueue state UNKNOWN group default
    link/ether fa:16:3e:41:8e:6b brd ff:ff:ff:ff:ff:ff
    inet 10.100.20.101/24 brd 10.100.20.255 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fc00:caa5:1:a:f816:3eff:fe30:16bf/64 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::fa16:3e00:541:8e6b/64 scope link
       valid_lft forever preferred_lft forever
```
When Pod(2) was created, our custom CNI sent gARP packet using this Go implementation. That is the first packet in the capture below. Inside Pod(2) I executed "arping -c1 -A -I eth1 10.100.20.101" (arping binary from centos repo) as a reference, that is the last packet in the capture file.

The problem is that the gARP packet send by this Go implementation is malformed (as it is reported by Wireshark v3), so I'm not sure whether it is really working.

The packet capture is attached here:
[garp.zip](https://github.com/j-keck/arping/files/3089195/garp.zip)

Can you please check what's wrong?
Thanks!

**Comment by j-keck** [comment]
I can't reproduce your problem on my side.

can you please test the arping executable from this repository on Pod(2)?

```
go get -u github.com/j-keck/arping/cmd/arping
sudo $GOPATH/bin/arping -v -U -i eth1 10.100.20.101
```

_if you don't like to use `sudo` for a executable from the internet, you can set the needed raw socket permission at first per `sudo setcap cap_net_raw+ep $GOPATH/bin/arping` and then use it without sudo._

Thanks.

**Comment by TothFerenc** [comment]
arping binary is also good:
[garp2.zip](https://github.com/j-keck/arping/files/3091420/garp2.zip)

Here you can find the code which produces malformed gARP packet:
https://github.com/TothFerenc/danm/blob/garp/pkg/danmep/ep.go#L121
Do you have any idea how it can be fixed? Thanks!

**Comment by j-keck** [comment]
Ok, i can reproduce a malformed arp packet when i use a v6 address.
**I think** this is a bug in this library - it should return a error, if someone try to use a v6 address.
But i need to read more about IPv6 / NDP at first (https://en.wikipedia.org/wiki/Neighbor_Discovery_Protocol).

Is it possible that you use a v6 address? Your test was with a v4 address.
Can you please log you ip to verify this?

Thanks

**Comment by TothFerenc** [comment]
I figured out what was the problem: our `ip` string contains prefixed IPv4 address, so I have to use `net.ParseCIDR()` instead of `net.ParseIP()`.
Anyway, `arping.GratuitousArpOverIfaceByName()` needs input validation. Better to report error instead of sending malformed ARP packets.
Thanks for your help.

**Comment by j-keck** [comment]
Yes, i need better input validation for all api calls (verify it's a v4 address **and** the ip is not nil).
I didn't know that an `net.IP` can have "an illegal state":  https://play.golang.org/p/Rv2r13IyaVM

Thanks for your reponses
