### ISSUE TITLE
goroutines leak

### ISSUE THREAD

**Issue by blankskygithub** [j-keck/arping#4]
**Use arping package like this:**
 ```
var arpSyncInterval := time.NewTicker(time.Second * 10)
 go loopForARP(dstIp);

 func loopForARP(dstIp) {
     for _ = range arpSyncInterval .C {
          mac, _, err := arping.Ping(dstIp)
          if err != nil {
			log.WithError(err).Errorf("send arp ping failed")
			continue
          }
          // doSomethingWithMac()
     }
}
```

The goroutines continuously **rising when dstIp is unreachable**. 
There are same goroutine like this:
![image](https://user-images.githubusercontent.com/12966967/77747986-91943c00-705a-11ea-9f9d-abbadeac3e01.png)

I review the code of arping.Ping(), expect that it will stop the goroutine when arping timeout. but the result doesn't meet.
![image](https://user-images.githubusercontent.com/12966967/77748645-ac1ae500-705b-11ea-8495-de4a8af02947.png)

Is the usage wrong for the arping package？or misunderstanding for the goroutine？

**Comment by j-keck** [comment]
Hello,

You are right - this is a silly bug.
I will look into it at the weekend.

Thanks for the report.

**Comment by blankskygithub** [comment]
> Hello,
> 
> 
> 
> You are right - this is a silly bug.
> 
> I will look into it at the weekend.
> 
> 
> 
> Thanks for the report.

Thanks for prompt reply.

**Comment by j-keck** [comment]
Hello,

i pushed a fix in the dev branch. 
Can you please test it on your site?
I tested it with a litte test programm (with `net/http/pprof`) and it works on my site.

Thanks, greetings Jürgen
